name: Build and Push to ECR

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions: write-all

concurrency:
  group: build-ecr-${{ github.ref_name }}-${{ github.sha }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  COMPONENT_NAME: 'aiml-private-librechat'

jobs:
  build-docker:
    runs-on: [dataplane, self-hosted, linux, x64, large]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Compute version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "version=${LATEST_TAG}" >> $GITHUB_OUTPUT
          fi

      - name: Prepare environment
        run: cp .env.example .env

      - name: Build and push Docker image
        uses: ./.github/actions/docker-build
        with:
          version: ${{ steps.version.outputs.version }}
          aws_role_arn: ${{ vars.AWS_DEPLOYMENT_ROLE_ARN }}
          context: .
          file: Dockerfile
          target: node
          ecr_repo: ${{ env.COMPONENT_NAME }}
